name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-11]
        compiler: [clang]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: MacOS setup
      run: |
        brew install autoconf automake pkg-config libtool docutils libxml2 gmp
        export PATH=${PATH}:/usr/local/opt/gettext/bin
        export PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgconfig"
        export LDFLAGS="-L/usr/local/opt/libxml2/lib"
        export CPPFLAGS="-I/usr/local/opt/xml2/include"
    - name: Setup clang
      run: |
        echo 'CC=clang' >> $GITHUB_ENV
        echo 'CXX=clang++' >> $GITHUB_ENV
    - name: Libtool
      run: |
        autoreconf -i
    - name: Use Makefile
      run: |
        mkdir build-release
        cd build-release
        export NON_RELEASE=1
        ln -s ../makerelease-osx.mk Makefile
        make
        pwd
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with: 
        name: upload-binary
        path: /Users/runner/work/aria2/aria2/build-release/aria2/bin/aria2c
